{
 "title": "__Graphcore Virtual-IPU System Monitoring",
 "tags": [
  "Graphcore IPU-M2000",
  "ARM",
  "linux",
  "Ubuntu 18.04"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "IPU Logical Elements",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vipu_num_agents", "legendFormat": "Agents" },
    { "expr": "vipu_num_clusters", "legendFormat": "Clusters" },
    { "expr": "vipu_num_partitions", "legendFormat": "Partitions" }
   ]
  },
  {
   "title": "Number of Attached IPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum1:2112\",job=\"node\"})",
     "legendFormat": "IPUM1"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum2:2112\",job=\"node\"})",
     "legendFormat": "IPUM2"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum3:2112\",job=\"node\"})",
     "legendFormat": "IPUM3"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum4:2112\",job=\"node\"})",
     "legendFormat": "IPUM4"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum5:2112\",job=\"node\"})",
     "legendFormat": "IPUM5"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum6:2112\",job=\"node\"})",
     "legendFormat": "IPUM6"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum7:2112\",job=\"node\"})",
     "legendFormat": "IPUM7"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum8:2112\",job=\"node\"})",
     "legendFormat": "IPUM8"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum9:2112\",job=\"node\"})",
     "legendFormat": "IPUM9"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum10:2112\",job=\"node\"})",
     "legendFormat": "IPUM10"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum11:2112\",job=\"node\"})",
     "legendFormat": "IPUM11"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum12:2112\",job=\"node\"})",
     "legendFormat": "IPUM12"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum13:2112\",job=\"node\"})",
     "legendFormat": "IPUM13"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum14:2112\",job=\"node\"})",
     "legendFormat": "IPUM14"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum15:2112\",job=\"node\"})",
     "legendFormat": "IPUM15"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",instance=\"ipum16:2112\",job=\"node\"})",
     "legendFormat": "IPUM16"
    },
    {
     "expr": "count(ipu_attached{host=\"Graphcore IPU-M2000\",job=\"node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "IPU-Link Error Counts",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "count(ipu_link_err_cnt) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Usage of Chassis Power(Watt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(chassis_power{host=\"Graphcore IPU-M2000\",job=\"node\", psu_id=\"\" })",
     "legendFormat": "Total Power"
    }
   ]
  },
  {
   "title": "Power Usage by IPU-M2000s(Watt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "chassis_power{host=\"Graphcore IPU-M2000\",job=\"node\", psu_id=\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IPU-M2000 Temperature(°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(chassis_temperature) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IPU-Tile Clock Speed(MHz)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ipu_tile_clk_speed) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chassis Fan Speed(RPM)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 22 },
   "targets": [
    { "expr": "avg(chassis_fan) by (instance)", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}