---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-graphcore-ipu-demo
spec:
  capacity:
    storage: 20G
  accessModes:
  - ReadWriteMany
  local:
    path: /graphcore-ipu-demo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [host207-ipusrv16]}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-graphcore-ipu-demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20G
  storageClassName: ""


---
apiVersion: v1
kind: Service
metadata:
  name: svc-ubuntu-tf22-apache2-00
spec:
  selector:
    svc: ubuntu-tf22-apache2-00
  ports:
  - port: 80
    targetPort: 8800

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-ubuntu-tf22-apache2-00
  labels:
    svc: ubuntu-tf22-apache2-00
spec:
  nodeSelector:
    kubernetes.io/hostname: host207-ipusrv16 
  containers:
  - name: container
    image: mkbahk/ubuntu-apache2-tf22-cpu:1.0
    volumeMounts:
    - name: graphcore-ipu-demo
      mountPath: /graphcore-ipu-demo
  volumes:
  - name : graphcore-ipu-demo
    persistentVolumeClaim:
      claimName: pvc-graphcore-ipu-demo 
  terminationGracePeriodSecs: 0